version: '3.8'

services:
  db:
    image: postgres:14-bullseye
    restart: always
    volumes:
      - ./data/db/database/data:/var/lib/postgresql/data
      - ./data/db/log:/var/log
    hostname: db
    healthcheck:
        test: ["CMD", "psql", "${DB_NAME}" , "-h", "localhost", "-p", "5432"]
        start_period: 10s
        interval: 5s
        timeout: 10s
        retries: 10
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    networks:
      - default

  promtail:
    image: grafana/promtail
    container_name: promtail
    command: -config.file=/etc/promtail/promtail.yaml
    restart: unless-stopped
    volumes:
      - ./promtail.yaml:/etc/promtail/promtail.yaml
      - ./data/loki/:/loki
      - ./data/postfix/log:/log/postfix/
      - ./data/db/log:/log/db/
    ports:
      - 9095:9095

  loki:
    image: grafana/loki
    container_name: loki
      #command: -config.file=/mnt/config/loki-config.yml
    restart: unless-stopped
    volumes:
      #- ./local-config.yaml:/mnt/config/loki-config.yml
      - ./data/loki/:/loki
    ports:
      - 3107:3100

  grafana:
    hostname: grafana
    image: grafana/grafana-oss
    networks:
      - default
    ports:
      - "3001:3000"
    volumes:
      - ./data/grafana/conf:/etc/grafana
      - ./data/grafana/data:/var/lib/grafana
  prometheus:
    hostname: prometheus
    image: prom/prometheus
    networks:
      - default
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  mailhog:
    hostname: mailhog
    image: mailhog/mailhog
    networks:
      - default
    ports:
      - "8025:8025"
  postfix:
    depends_on:
      db:
        condition: service_healthy
    image: asrall_postfix
    hostname: postfix
    build:
      context: ./postfix
      args:
         - "https_proxy=${HTTP_PROXY}"
         - "http_proxy=${HTTP_PROXY}"
    environment:
      MIO_METHOD: "policy_toto"
      MAILNAME: "mio.test.net"
      POSTFIX_DOMAIN: "${POSTFIX_DOMAIN}"
      DB_HOST: 'db'
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
    volumes:
       - ./data/postfix/spool:/var/spool/postfix
       - ./data/postfix/log:/var/log/
    networks:
      - default
    ports:
      - "5000:5000"
      - "2525:25"
