version: '3.1'

services:
  db:
    image: postgres:14-bullseye
    restart: always
    volumes:
      - ./data/db/database/data:/var/lib/postgresql/data
      - ./data/db/log:/var/log
    hostname: db
    healthcheck:
        test: ["CMD", "psql", "${DB_NAME}" , "-h", "localhost", "-p", "5432"]
        start_period: 10s
        interval: 5s
        timeout: 10s
        retries: 10
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - default

  mailhog:
    hostname: mailhog
    image: mailhog/mailhog
    networks:
      - default
    ports:
      - 8025:8025
  postfix:
    depends_on:
      db:
        condition: service_healthy
    image: asrall_postfix
    hostname: postfix
    build:
      context: ./postfix
      args:
         - "https_proxy=http://webproxy.coe.int:8080"
         - "http_proxy=http://webproxy.coe.int:8080"
    environment:
      MIO_METHOD: "policy_toto"
      MAILNAME: "mio.test.net"
      POSTFIX_DOMAIN: toto.com=[mailhog]:1025;titi.com=[mailhog]:1025;test.net=[mailhog]:1025
      DB_HOST: 'db'
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    volumes:
       - ./data/postfix/spool:/var/spool/postfix
       - ./data/postfix/log:/var/log/
    networks:
      - default
    ports:
      - 5000:5000
      - 2525:25
